package org.eclipse.swt.internal.mozilla;

import java.StdTypes;
@:native("org.eclipse.swt.internal.mozilla.nsIDOMKeyEvent")
extern class NsIDOMKeyEvent extends org.eclipse.swt.internal.mozilla.NsIDOMUIEvent 
{
	inline static public var NS_IDOMKEYEVENT_IID_STR:String = "028e0e6e-8b01-11d3-aae7-0010838a3123";
	inline static public var NS_IDOMKEYEVENT_10_IID_STR:String = "def974c3-b491-481b-bc67-29174af4b26a";
	static public var NS_IDOMKEYEVENT_IID:org.eclipse.swt.internal.mozilla.NsID;
	static public var NS_IDOMKEYEVENT_10_IID:org.eclipse.swt.internal.mozilla.NsID;
	inline static public var DOM_VK_CANCEL:Int = 3;
	inline static public var DOM_VK_HELP:Int = 6;
	inline static public var DOM_VK_BACK_SPACE:Int = 8;
	inline static public var DOM_VK_TAB:Int = 9;
	inline static public var DOM_VK_CLEAR:Int = 12;
	inline static public var DOM_VK_RETURN:Int = 13;
	inline static public var DOM_VK_ENTER:Int = 14;
	inline static public var DOM_VK_SHIFT:Int = 16;
	inline static public var DOM_VK_CONTROL:Int = 17;
	inline static public var DOM_VK_ALT:Int = 18;
	inline static public var DOM_VK_PAUSE:Int = 19;
	inline static public var DOM_VK_CAPS_LOCK:Int = 20;
	inline static public var DOM_VK_ESCAPE:Int = 27;
	inline static public var DOM_VK_SPACE:Int = 32;
	inline static public var DOM_VK_PAGE_UP:Int = 33;
	inline static public var DOM_VK_PAGE_DOWN:Int = 34;
	inline static public var DOM_VK_END:Int = 35;
	inline static public var DOM_VK_HOME:Int = 36;
	inline static public var DOM_VK_LEFT:Int = 37;
	inline static public var DOM_VK_UP:Int = 38;
	inline static public var DOM_VK_RIGHT:Int = 39;
	inline static public var DOM_VK_DOWN:Int = 40;
	inline static public var DOM_VK_PRINTSCREEN:Int = 44;
	inline static public var DOM_VK_INSERT:Int = 45;
	inline static public var DOM_VK_DELETE:Int = 46;
	inline static public var DOM_VK_0:Int = 48;
	inline static public var DOM_VK_1:Int = 49;
	inline static public var DOM_VK_2:Int = 50;
	inline static public var DOM_VK_3:Int = 51;
	inline static public var DOM_VK_4:Int = 52;
	inline static public var DOM_VK_5:Int = 53;
	inline static public var DOM_VK_6:Int = 54;
	inline static public var DOM_VK_7:Int = 55;
	inline static public var DOM_VK_8:Int = 56;
	inline static public var DOM_VK_9:Int = 57;
	inline static public var DOM_VK_SEMICOLON:Int = 59;
	inline static public var DOM_VK_EQUALS:Int = 61;
	inline static public var DOM_VK_A:Int = 65;
	inline static public var DOM_VK_B:Int = 66;
	inline static public var DOM_VK_C:Int = 67;
	inline static public var DOM_VK_D:Int = 68;
	inline static public var DOM_VK_E:Int = 69;
	inline static public var DOM_VK_F:Int = 70;
	inline static public var DOM_VK_G:Int = 71;
	inline static public var DOM_VK_H:Int = 72;
	inline static public var DOM_VK_I:Int = 73;
	inline static public var DOM_VK_J:Int = 74;
	inline static public var DOM_VK_K:Int = 75;
	inline static public var DOM_VK_L:Int = 76;
	inline static public var DOM_VK_M:Int = 77;
	inline static public var DOM_VK_N:Int = 78;
	inline static public var DOM_VK_O:Int = 79;
	inline static public var DOM_VK_P:Int = 80;
	inline static public var DOM_VK_Q:Int = 81;
	inline static public var DOM_VK_R:Int = 82;
	inline static public var DOM_VK_S:Int = 83;
	inline static public var DOM_VK_T:Int = 84;
	inline static public var DOM_VK_U:Int = 85;
	inline static public var DOM_VK_V:Int = 86;
	inline static public var DOM_VK_W:Int = 87;
	inline static public var DOM_VK_X:Int = 88;
	inline static public var DOM_VK_Y:Int = 89;
	inline static public var DOM_VK_Z:Int = 90;
	inline static public var DOM_VK_NUMPAD0:Int = 96;
	inline static public var DOM_VK_NUMPAD1:Int = 97;
	inline static public var DOM_VK_NUMPAD2:Int = 98;
	inline static public var DOM_VK_NUMPAD3:Int = 99;
	inline static public var DOM_VK_NUMPAD4:Int = 100;
	inline static public var DOM_VK_NUMPAD5:Int = 101;
	inline static public var DOM_VK_NUMPAD6:Int = 102;
	inline static public var DOM_VK_NUMPAD7:Int = 103;
	inline static public var DOM_VK_NUMPAD8:Int = 104;
	inline static public var DOM_VK_NUMPAD9:Int = 105;
	inline static public var DOM_VK_MULTIPLY:Int = 106;
	inline static public var DOM_VK_ADD:Int = 107;
	inline static public var DOM_VK_SEPARATOR:Int = 108;
	inline static public var DOM_VK_SUBTRACT:Int = 109;
	inline static public var DOM_VK_DECIMAL:Int = 110;
	inline static public var DOM_VK_DIVIDE:Int = 111;
	inline static public var DOM_VK_F1:Int = 112;
	inline static public var DOM_VK_F2:Int = 113;
	inline static public var DOM_VK_F3:Int = 114;
	inline static public var DOM_VK_F4:Int = 115;
	inline static public var DOM_VK_F5:Int = 116;
	inline static public var DOM_VK_F6:Int = 117;
	inline static public var DOM_VK_F7:Int = 118;
	inline static public var DOM_VK_F8:Int = 119;
	inline static public var DOM_VK_F9:Int = 120;
	inline static public var DOM_VK_F10:Int = 121;
	inline static public var DOM_VK_F11:Int = 122;
	inline static public var DOM_VK_F12:Int = 123;
	inline static public var DOM_VK_F13:Int = 124;
	inline static public var DOM_VK_F14:Int = 125;
	inline static public var DOM_VK_F15:Int = 126;
	inline static public var DOM_VK_F16:Int = 127;
	inline static public var DOM_VK_F17:Int = 128;
	inline static public var DOM_VK_F18:Int = 129;
	inline static public var DOM_VK_F19:Int = 130;
	inline static public var DOM_VK_F20:Int = 131;
	inline static public var DOM_VK_F21:Int = 132;
	inline static public var DOM_VK_F22:Int = 133;
	inline static public var DOM_VK_F23:Int = 134;
	inline static public var DOM_VK_F24:Int = 135;
	inline static public var DOM_VK_NUM_LOCK:Int = 144;
	inline static public var DOM_VK_SCROLL_LOCK:Int = 145;
	inline static public var DOM_VK_COMMA:Int = 188;
	inline static public var DOM_VK_PERIOD:Int = 190;
	inline static public var DOM_VK_SLASH:Int = 191;
	inline static public var DOM_VK_BACK_QUOTE:Int = 192;
	inline static public var DOM_VK_OPEN_BRACKET:Int = 219;
	inline static public var DOM_VK_BACK_SLASH:Int = 220;
	inline static public var DOM_VK_CLOSE_BRACKET:Int = 221;
	inline static public var DOM_VK_QUOTE:Int = 222;
	inline static public var DOM_VK_META:Int = 224;
	inline static public var DOM_VK_KANA:Int = 21;
	inline static public var DOM_VK_HANGUL:Int = 21;
	inline static public var DOM_VK_JUNJA:Int = 23;
	inline static public var DOM_VK_FINAL:Int = 24;
	inline static public var DOM_VK_HANJA:Int = 25;
	inline static public var DOM_VK_KANJI:Int = 25;
	inline static public var DOM_VK_CONVERT:Int = 28;
	inline static public var DOM_VK_NONCONVERT:Int = 29;
	inline static public var DOM_VK_ACCEPT:Int = 30;
	inline static public var DOM_VK_MODECHANGE:Int = 31;
	inline static public var DOM_VK_SELECT:Int = 41;
	inline static public var DOM_VK_PRINT:Int = 42;
	inline static public var DOM_VK_EXECUTE:Int = 43;
	inline static public var DOM_VK_CONTEXT_MENU:Int = 93;
	inline static public var DOM_VK_SLEEP:Int = 95;
	public function new(address:haxe.Int64):Void;
	public function InitKeyEvent(typeArg:haxe.Int64,canBubbleArg:Int,cancelableArg:Int,viewArg:haxe.Int64,ctrlKeyArg:Int,altKeyArg:Int,shiftKeyArg:Int,metaKeyArg:Int,keyCodeArg:Int,charCodeArg:Int):Int;
	public function GetMetaKey(aMetaKey:java.NativeArray<Int>):Int;
	public function GetShiftKey(aShiftKey:java.NativeArray<Int>):Int;
	public function GetCtrlKey(aCtrlKey:java.NativeArray<Int>):Int;
	public function GetCharCode(aCharCode:java.NativeArray<Int>):Int;
	public function GetAltKey(aAltKey:java.NativeArray<Int>):Int;
	public function GetKeyCode(aKeyCode:java.NativeArray<Int>):Int;

}
